name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist/client
